from __future__ import annotations

import streamlit as st

from components.form_state import field_key
from components.ui_components import step_header
from services import report_service


def render(draft: dict, technician: str) -> None:
    step_header(4, "Basic Details")
    c1, c2 = st.columns(2)
    for col, field, label in ((c1, "collection_date", "Sample Collection Date"),
                              (c2, "analysis_date", "Sample Analysis Date")):
        draft[field] = col.date_input(label, key=field_key(draft, field, draft.get(field)),
                                     format="DD-MM-YYYY")
    mode = st.radio(
        "Client details", ["Available", "N/A — Third-Party Sample Testing"],
        key=field_key(draft, "client_details_mode",
                      "N/A — Third-Party Sample Testing" if draft.get("third_party_sample") else "Available"),
        horizontal=True,
    )
    draft["third_party_sample"] = mode != "Available"
    if draft["third_party_sample"]:
        st.caption("Client identity and contact details are not required and will be omitted from the report.")
    else:
        clients = report_service.list_clients()
        names = [c["name"] for c in clients]
        if draft.get("client_name") and draft["client_name"] not in names:
            names.append(draft["client_name"])
        sel = st.selectbox("Client Name", [""] + names,
                           key=field_key(draft, "client_name", draft.get("client_name", "")))
        if sel != draft.get("client_name"):
            draft["client_name"] = sel
            match = next((c for c in clients if c["name"] == sel), None)
            if match:
                for field, source in (("client_address", "address"), ("contact_person", "contact_person"),
                                      ("client_email", "email"), ("assigned_technician", "assigned_technician"),
                                      ("assigned_employee_id", "assigned_employee_id"), ("office", "office")):
                    draft[field] = match[source]
                    st.session_state[field_key(draft, field)] = match[source]
        draft["client_address"] = st.text_area("Address", key=field_key(draft, "client_address", draft.get("client_address", "")), height=70)
        draft["contact_person"] = st.text_input("Contact Person", key=field_key(draft, "contact_person", draft.get("contact_person", "")))
        st.text_input("Client Email", value=draft.get("client_email", ""), disabled=True)
        st.text_input("Assigned Technician", value=draft.get("assigned_technician", ""), disabled=True)
    draft["technician"] = technician
    st.text_input("Report generated by", value=technician, disabled=True)
